export const defaultCategories = [
  {
    id: 1,
    name: 'Alimentation & Terroir',
    slug: 'alimentation-epices',
    description: 'Piments, miels locaux purs et produits agricoles certifiés.',
    image: '/images/products/epices.jpg',
    icon: 'restaurant_menu',
    count: 0,
  },
  {
    id: 2,
    name: 'Art & Sculpture',
    slug: 'artisanat',
    description: 'Bois précieux et statues directement issues des palais royaux.',
    image: '/images/products/art.jpg',
    icon: 'palette',
    count: 0,
  },
  {
    id: 3,
    name: 'Mode & Textile',
    slug: 'mode-textile',
    description: "Kanvô authentique, pagnes tissés à l'ancienne, et parures.",
    image: '/images/products/wax.jpg',
    icon: 'checkroom',
    count: 0,
  },
  {
    id: 4,
    name: 'Maison & Décoration',
    slug: 'maison-deco',
    description: 'Poteries de Sè ancestrales et vanneries solides.',
    image: '/images/products/maison.jpg',
    icon: 'chair',
    count: 0,
  },
]

export const defaultProducts = [
  {
    id: 1,
    slug: 'statue-roi-dahomey',
    nom: 'Statue Roi Dahomey',
    lieu: 'Abomey',
    prix: 45000,
    badge: 'Mis en avant',
    note: 4.9,
    categorie: 'recent',
    image: '/images/products/art.jpg',
    stock: 3,
  },
  {
    id: 2,
    slug: 'pagne-tisse-akpet',
    nom: 'Pagne Tissé Akpè',
    lieu: 'Cotonou',
    prix: 15000,
    badge: '',
    note: 4.7,
    categorie: 'recent',
    image: '/images/products/wax.jpg',
    stock: 12,
  },
  {
    id: 3,
    slug: 'miel-pur-para',
    nom: 'Miel Pur Parakou',
    lieu: 'Parakou',
    prix: 3500,
    badge: 'Terroir & Bio',
    note: 5.0,
    categorie: 'bio',
    image: '/images/products/miel.jpg',
    stock: 25,
  },
  {
    id: 4,
    slug: 'vase-ceramique-se',
    nom: 'Vase Céramique Sè',
    lieu: 'Sè',
    prix: 28000,
    badge: 'Très Demandé',
    note: 4.8,
    categorie: 'tendance',
    image: '/images/products/maison.jpg',
    stock: 5,
  },
]

export const defaultShops = [
  {
    id: 'atelier-kanvo',
    nom: 'Atelier Kanvô',
    subtitle: 'Abomey, Bénin',
    avatar: 'https://ui-avatars.com/api/?name=Atelier+Kanvo&background=1B6B3A&color=fff&size=200',
    quote: 'Artisan traditionnel depuis 3 générations, je crée des œuvres qui honorent nos ancêtres.',
    extra: 12,
  },
  {
    id: 'monteiro-fashion',
    nom: 'Monteiro Fashion',
    subtitle: 'Cotonou, Bénin',
    avatar: 'https://ui-avatars.com/api/?name=Monteiro+Fashion&background=D4920A&color=fff&size=200',
    quote: 'Le plus beau du Kanvô authentique, tissé à la main avec délicatesse et passion.',
    extra: 18,
  },
  {
    id: 'kaba-et-fils',
    nom: 'Kaba & Fils',
    subtitle: 'Dassa-Zoumé, Bénin',
    avatar: 'https://ui-avatars.com/api/?name=Kaba+Fils&background=EAB308&color=fff&size=200',
    quote: 'Miel 100% pur et naturel directement des ruchers du Nord, récolté à la main.',
    extra: 9,
  },
]