export const defaultCategories = [
  {
    id: 1,
    name: 'Alimentation & Terroir',
    slug: 'alimentation-epices',
    description: 'Piments, miels locaux purs et produits agricoles certifiés.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=600',
    icon: 'restaurant_menu',
  },
  {
    id: 2,
    name: 'Art & Sculpture',
    slug: 'artisanat',
    description: 'Bois précieux et statues directement issues des palais royaux.',
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&q=80&w=600',
    icon: 'palette',
  },
  {
    id: 3,
    name: 'Mode & Textile',
    slug: 'mode-textile',
    description: "Kanvô authentique, pagnes tissés à l'ancienne, et parures.",
    image: 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&q=80&w=600',
    icon: 'checkroom',
  },
  {
    id: 4,
    name: 'Maison & Décoration',
    slug: 'maison-deco',
    description: 'Poteries de Sè ancestrales et vanneries solides.',
    image: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&q=80&w=600',
    icon: 'chair',
  },
]

export const defaultProducts = [
  {
    id: 1,
    slug: 'statue-roi-dahomey',
    nom: 'Statue Roi Dahomey',
    lieu: 'Abomey',
    prix: 45000,
    badge: 'Mis en avant',
    categorie: 'recent',
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&q=80&w=600',
    stock: 3,
  },
  {
    id: 2,
    slug: 'pagne-tisse-akpet',
    nom: 'Pagne Tissé Akpè',
    lieu: 'Cotonou',
    prix: 15000,
    badge: '',
    categorie: 'recent',
    image: 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&q=80&w=600',
    stock: 12,
  },
  {
    id: 3,
    slug: 'miel-pur-para',
    nom: 'Miel Pur Para',
    lieu: 'Parakou',
    prix: 3500,
    badge: 'Terroir & Bio',
    categorie: 'bio',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=600',
    stock: 25,
  },
  {
    id: 4,
    slug: 'vase-ceramique-se',
    nom: 'Vase Céramique Sè',
    lieu: 'Sè',
    prix: 28000,
    badge: 'Très Demandé',
    categorie: 'tendance',
    image: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&q=80&w=600',
    stock: 5,
  },
]

export const defaultShops = [
  {
    id: 'atelier-esclava',
    nom: 'Atelier Esclava',
    subtitle: 'Cotonou, Béninoise',
    avatar: 'https://ui-avatars.com/api/?name=Atelier+Esclava&background=1B6B3A&color=fff&size=200',
    quote: 'Artisan traditionnel depuis 3 générations, je crée des œuvres qui honorent nos ancêtres.',
    extra: 8,
  },
  {
    id: 'tissages-da',
    nom: 'Tissages Da',
    subtitle: 'Abomey, Béninoise',
    avatar: 'https://ui-avatars.com/api/?name=Tissages+Da&background=D4920A&color=fff&size=200',
    quote: 'Le plus beau du Kanvô authentique, tissé à la main avec délicatesse.',
    extra: 15,
  },
  {
    id: 'miel-parad',
    nom: 'Miel ParaD',
    subtitle: 'Parakou, Béninois',
    avatar: 'https://ui-avatars.com/api/?name=Miel+ParaD&background=EAB308&color=fff&size=200',
    quote: 'Miel 100% pur et naturel directement des ruchers du Nord.',
    extra: 6,
  },
]